name: Node.js Express App Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test # هذا يعتمد على إذا كان لديك اختبارات أم لا، يمكنك تجاهل هذه الخطوة إذا لم تكن بحاجة لها

    - name: Start the application
      run: node your_app_file.js # تأكد من استبدال "your_app_file.js" بالملف الرئيسي لمشروعك
      env:
        PORT: 5000
        NODE_ENV: production
